spring:
  application:
    name: Friend Finder
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB
    username: FRIEND_FINDER
    password: FRIEND_FINDER
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    basename: i18n/messages
    local-default: en
    encoding: UTF-8
  main:
    allow-circular-references: true
server:
  port: 8085

token:
  secret: kkkjgkhkd669$#65@#fghdfyhrtyerytryrtydfgjfg
  time: 10h